// models/glass.ts
import { ObjectId } from "mongodb";

// ROI object (optional in tokens)
export interface Roi {
  times: number;
  currency: string;
  percentage: number;
}

// Token structure (common to all lists)
export interface Token {
  id: string;
  symbol: string;
  name: string;
  image: string;
  price: number;
  marketCap: number;
  rank: number;
  volume: number;
  change24h: number;
  percentChange24h: number;
  roi?: Roi; // Optional
}

// Counts for each list
export interface Counts {
  top15MarketCap: number;
  top12Performance: number;
  bestBelowThreshold: number;
  worstBelowThreshold: number;
  positiveTop12: number;
}

// Main document structure
export interface Glass {
  _id?: ObjectId; // Auto-generated by MongoDB
  success: boolean;
  top15MarketCap: Token[];
  top12Performance: Token[];
  bestBelowThreshold: Token[];
  worstBelowThreshold: Token[];
  threshold: number;
  worstThreshold: number; // Adicionado aqui
  marketStatus: string;
  counts: Counts;
  createdAt: Date;
  updatedAt: Date;
}